apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-tomcat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-tomcatn
  template:
    metadata:
      labels:
        app: my-tomcat
    spec:
      containers:
      - name: my-tomcat
        image: bhargavilakamsani/tomcat:latest
        ports:
        - containerPort: 8080
