replicaCount: 3  # Increase for high availability

image:
  repository: bhargavilakamsani/tomcatnew
  pullPolicy: IfNotPresent
  tag: "14"  # Or use a variable like ${BUILD_NUMBER} for dynamic tagging

imagePullSecrets:
  - name: my-registry-secret  # If you use a private registry

serviceAccount:
  create: true
  name: custom-service-account  # Optional: specify a custom name if needed

podSecurityContext:
  fsGroup: 2000  # Example: set to your requirements

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: LoadBalancer  # Ensure this matches your environment
